# Generated by Django 3.1.6 on 2021-02-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True, verbose_name='Username')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Full name')),
                ('phone_number', models.CharField(max_length=20, null=True, verbose_name='Phone number')),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('uz', 'Uzbek'), ('en', 'English')], max_length=2, null=True, verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
