# Generated by Django 3.1.6 on 2021-02-15 12:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Residence',
                'verbose_name_plural': 'Residences',
            },
        ),
        migrations.CreateModel(
            name='RoomQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
            ],
            options={
                'verbose_name': 'Room quantity',
                'verbose_name_plural': 'Room quantities',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(null=True, verbose_name='Completed at')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='lead.customer', verbose_name='Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square', models.FloatField(verbose_name='Square')),
                ('description', models.CharField(max_length=4000, verbose_name='Description')),
                ('files', models.ManyToManyField(related_name='apartments', to='lead.File', verbose_name='Files')),
                ('photos', models.ManyToManyField(related_name='apartments', to='lead.Photo', verbose_name='Photos')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='lead.residence', verbose_name='Residence')),
                ('room_quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='lead.roomquantity', verbose_name='Room quantity')),
            ],
        ),
    ]
