# Generated by Django 3.1.6 on 2021-02-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_auto_20210219_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='apartments', to='lead.File', verbose_name='Files'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='apartments', to='lead.Video', verbose_name='Videos'),
        ),
    ]
