# Generated by Django 3.1.6 on 2021-03-19 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_auto_20210225_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='apartment_choice_photo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residence', to='lead.photo', verbose_name='Apartment choice photo'),
        ),
    ]
