# Generated by Django 3.1.6 on 2021-02-19 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_auto_20210219_1936'),
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informationfile',
            options={'verbose_name': 'Information file', 'verbose_name_plural': 'Information file'},
        ),
        migrations.AlterModelOptions(
            name='informationphoto',
            options={'verbose_name': 'Information photo', 'verbose_name_plural': 'Information photo'},
        ),
        migrations.AlterModelOptions(
            name='informationtext',
            options={'verbose_name': 'Information text', 'verbose_name_plural': 'Information text'},
        ),
        migrations.CreateModel(
            name='InformationVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='information_video', to='lead.video', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Information video',
                'verbose_name_plural': 'Information video',
            },
        ),
    ]
