# Generated by Django 3.1.6 on 2021-02-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20210219_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informationfile',
            options={'verbose_name': 'Information file', 'verbose_name_plural': 'Information files'},
        ),
        migrations.AlterModelOptions(
            name='informationphoto',
            options={'verbose_name': 'Information photo', 'verbose_name_plural': 'Information photos'},
        ),
        migrations.AlterModelOptions(
            name='informationvideo',
            options={'verbose_name': 'Information video', 'verbose_name_plural': 'Information videos'},
        ),
    ]
